
// Enhanced category-to-image mappings with specific IDs and more precise keywords
export const CATEGORIES = {
  nature: [
    { id: 15, keywords: ["mountain", "outdoor", "landscape", "hill", "nature", "scenic view"] },
    { id: 33, keywords: ["forest", "trees", "green", "woods", "woodland", "pine", "evergreen"] },
    { id: 37, keywords: ["valley", "scenic", "hills", "countryside", "grassland", "meadow"] },
    { id: 110, keywords: ["lake", "water", "serene", "pond", "reflection", "calm water"] },
    { id: 64, keywords: ["beach", "ocean", "coast", "sea", "sand", "shore", "waves", "tropical"] },
    { id: 76, keywords: ["flowers", "garden", "blooms", "floral", "botanical", "rose", "tulip"] },
    { id: 1018, keywords: ["snow", "winter", "cold", "ice", "frost", "snowy", "frozen"] },
    { id: 106, keywords: ["waterfall", "cascade", "flowing", "stream", "river", "water flow"] },
  ],
  cityscape: [
    { id: 260, keywords: ["skyline", "downtown", "city", "metropolis", "urban", "cityscape"] },
    { id: 452, keywords: ["buildings", "architecture", "urban", "structure", "skyscraper", "tower"] },
    { id: 429, keywords: ["street", "road", "city life", "avenue", "boulevard", "urban street"] },
    { id: 172, keywords: ["night city", "lights", "urban night", "evening", "nightlife", "city lights"] },
    { id: 315, keywords: ["bridge", "infrastructure", "crossing", "span", "connection", "suspension"] },
    { id: 238, keywords: ["urban landscape", "metropolis", "city view", "downtown view"] },
  ],
  portrait: [
    { id: 338, keywords: ["woman", "female", "portrait", "girl", "lady", "female portrait"] },
    { id: 823, keywords: ["man", "male", "portrait", "guy", "gentleman", "male portrait"] },
    { id: 660, keywords: ["child", "kid", "young", "youth", "toddler", "childhood"] },
    { id: 26, keywords: ["old person", "elderly", "aged", "senior", "retiree", "wise"] },
    { id: 453, keywords: ["group", "people", "crowd", "gathering", "audience", "team"] },
    { id: 177, keywords: ["portrait", "face", "headshot", "person", "model", "close-up"] },
    { id: 334, keywords: ["smile", "happy face", "joy", "cheerful", "grin", "happiness"] },
  ],
  abstract: [
    { id: 1084, keywords: ["pattern", "geometric", "shapes", "design", "motif", "abstract pattern"] },
    { id: 447, keywords: ["colorful", "vibrant", "bright", "multicolored", "rainbow", "vivid"] },
    { id: 1069, keywords: ["abstract", "artistic", "non-representational", "surreal", "modern art"] },
    { id: 1020, keywords: ["texture", "surface", "material", "background", "canvas", "fabric"] },
    { id: 30, keywords: ["minimalist", "simple", "clean", "minimal design", "basic"] },
  ],
  animals: [
    { id: 237, keywords: ["dog", "canine", "pet", "puppy", "hound", "doggy", "pooch"] },
    { id: 40, keywords: ["cat", "feline", "pet", "kitten", "domestic animal", "kitty"] },
    { id: 582, keywords: ["bird", "avian", "flying", "feathered", "wings", "feathers"] },
    { id: 790, keywords: ["wildlife", "wild animal", "nature", "fauna", "creature", "natural"] },
    { id: 659, keywords: ["horse", "equine", "mammal", "pony", "stallion", "mare"] },
    { id: 219, keywords: ["bear", "grizzly", "wildlife", "predator", "mammal", "brown bear"] },
    { id: 433, keywords: ["lion", "big cat", "predator", "jungle", "safari", "wildcat"] },
    { id: 146, keywords: ["fox", "wildlife", "red fox", "canine", "wild dog", "forest animal"] },
    { id: 200, keywords: ["tiger", "big cat", "stripes", "jungle", "feline", "predator"] },
    { id: 211, keywords: ["wolf", "wild", "canine", "predator", "pack animal", "wilderness"] },
  ],
  technology: [
    { id: 0, keywords: ["computer", "tech", "device", "laptop", "digital", "electronics"] },
    { id: 48, keywords: ["digital", "screen", "display", "monitor", "electronic", "technology"] },
    { id: 160, keywords: ["robot", "ai", "machine", "automation", "artificial intelligence", "robotic"] },
    { id: 370, keywords: ["futuristic", "sci-fi", "future", "advanced", "innovation", "high-tech"] },
    { id: 1056, keywords: ["gadget", "electronic", "device", "equipment", "smart", "technological"] },
    { id: 404, keywords: ["code", "programming", "software", "development", "technology", "coding"] },
    { id: 367, keywords: ["circuit", "electronic", "microchip", "processor", "technology"] },
  ],
  food: [
    { id: 292, keywords: ["meal", "dish", "plate", "dinner", "lunch", "food", "cuisine"] },
    { id: 1080, keywords: ["fruit", "healthy", "fresh", "produce", "nutritious", "organic"] },
    { id: 225, keywords: ["dessert", "sweet", "cake", "pastry", "confection", "bakery"] },
    { id: 493, keywords: ["vegetable", "greens", "produce", "healthy", "organic", "veggies"] },
    { id: 132, keywords: ["drink", "beverage", "liquid", "refreshment", "cup", "glass"] },
    { id: 42, keywords: ["coffee", "cafe", "espresso", "latte", "brew", "caffeine"] },
    { id: 431, keywords: ["pizza", "italian", "fast food", "cheese", "tomato", "slice"] },
    { id: 239, keywords: ["burger", "hamburger", "fast food", "sandwich", "beef", "bun"] },
  ],
  art: [
    { id: 200, keywords: ["painting", "artwork", "canvas", "masterpiece", "artistic", "art"] },
    { id: 349, keywords: ["drawing", "sketch", "illustration", "graphic", "pencil", "art"] },
    { id: 674, keywords: ["sculpture", "statue", "3d art", "carving", "monument", "artistic"] },
    { id: 423, keywords: ["masterpiece", "classic", "famous", "renowned", "celebrated", "artwork"] },
    { id: 628, keywords: ["creative", "artistic", "imaginative", "inventive", "innovative", "artistic"] },
    { id: 59, keywords: ["graffiti", "street art", "urban art", "spray paint", "mural"] },
  ],
  space: [
    { id: 701, keywords: ["stars", "galaxy", "universe", "cosmos", "celestial", "night sky"] },
    { id: 808, keywords: ["planets", "solar system", "cosmic", "orbital", "space", "astronomical"] },
    { id: 683, keywords: ["nebula", "space cloud", "astronomical", "stellar", "cosmic dust"] },
    { id: 717, keywords: ["space", "cosmic", "astronomy", "interstellar", "void", "universe"] },
    { id: 43, keywords: ["moon", "lunar", "night sky", "celestial body", "satellite"] },
  ],
  fantasy: [
    { id: 326, keywords: ["magical", "fantasy", "mythical", "enchanted", "mystical", "fairytale"] },
    { id: 611, keywords: ["dragon", "creature", "mythological", "beast", "legendary", "fantasy"] },
    { id: 867, keywords: ["medieval", "castle", "kingdom", "fortress", "ancient", "historical"] },
    { id: 501, keywords: ["fairy", "magical being", "enchanted", "fantasy creature", "pixie"] },
    { id: 235, keywords: ["unicorn", "mythical", "fantasy", "magical creature", "legend"] },
    { id: 445, keywords: ["wizard", "magic", "sorcery", "mystical", "spell", "magical"] },
  ],
  transportation: [
    { id: 111, keywords: ["car", "vehicle", "automobile", "transportation", "wheels", "driving"] },
    { id: 191, keywords: ["airplane", "aircraft", "flight", "aviation", "flying", "plane"] },
    { id: 1073, keywords: ["train", "locomotive", "railway", "track", "transit", "rail"] },
    { id: 331, keywords: ["boat", "ship", "vessel", "nautical", "sailing", "watercraft"] },
    { id: 513, keywords: ["motorcycle", "bike", "motorbike", "cycling", "biker", "chopper"] },
  ],
  business: [
    { id: 119, keywords: ["office", "business", "workspace", "corporate", "professional", "work"] },
    { id: 1011, keywords: ["meeting", "conference", "discussion", "collaboration", "teamwork"] },
    { id: 90, keywords: ["laptop", "computer", "work", "business", "desk", "workplace"] },
    { id: 201, keywords: ["handshake", "agreement", "deal", "partnership", "business"] },
  ],
  architecture: [
    { id: 342, keywords: ["modern architecture", "contemporary", "building", "design", "structure"] },
    { id: 164, keywords: ["church", "religious", "historic", "cathedral", "temple", "worship"] },
    { id: 309, keywords: ["ancient", "historic", "old", "ruins", "archeological", "historical"] },
    { id: 678, keywords: ["mansion", "luxury home", "estate", "grand house", "villa"] },
  ],
  seasons: [
    { id: 82, keywords: ["autumn", "fall", "leaves", "seasonal", "orange", "falling leaves"] },
    { id: 726, keywords: ["spring", "bloom", "flowers", "seasonal", "rebirth", "blossoms"] },
    { id: 139, keywords: ["summer", "hot", "sunny", "beach", "vacation", "warmth"] },
    { id: 325, keywords: ["winter", "cold", "snow", "seasonal", "ice", "freezing"] },
  ],
  weather: [
    { id: 96, keywords: ["storm", "lightning", "thunder", "rain", "heavy weather", "tempest"] },
    { id: 19, keywords: ["fog", "mist", "hazy", "foggy", "atmospheric", "misty"] },
    { id: 345, keywords: ["sunshine", "sunny", "bright", "sunlight", "clear sky", "sunny day"] },
    { id: 29, keywords: ["clouds", "cloudy", "overcast", "sky", "weather", "atmosphere"] },
  ],
  sports: [
    { id: 209, keywords: ["soccer", "football", "sport", "game", "ball", "team sport"] },
    { id: 258, keywords: ["basketball", "sport", "game", "court", "ball", "team sport"] },
    { id: 321, keywords: ["tennis", "sport", "game", "racket", "court", "ball"] },
    { id: 178, keywords: ["swimming", "water sport", "pool", "aquatic", "swim", "water"] },
  ],
  vehicles: [
    { id: 133, keywords: ["sports car", "fast", "luxury", "racing", "performance", "speed"] },
    { id: 193, keywords: ["truck", "transport", "pickup", "cargo", "delivery", "heavy duty"] },
    { id: 655, keywords: ["bicycle", "bike", "cycling", "pedal", "transportation", "eco"] },
    { id: 1072, keywords: ["helicopter", "aircraft", "flying", "chopper", "aviation"] },
  ],
  style: [
    { id: 461, keywords: ["vintage", "retro", "old-fashioned", "classic", "nostalgic", "old"] },
    { id: 372, keywords: ["modern", "contemporary", "current", "present-day", "sleek"] },
    { id: 304, keywords: ["rustic", "country", "rural", "natural", "aged", "weathered"] },
    { id: 425, keywords: ["elegant", "sophisticated", "refined", "graceful", "stylish"] },
  ]
};
