
// Enhanced category-to-image mappings with specific IDs and more precise keywords
export const CATEGORIES = {
  nature: [
    { id: 15, keywords: ["mountain", "outdoor", "landscape", "hill", "nature"] },
    { id: 33, keywords: ["forest", "trees", "green", "woods", "woodland"] },
    { id: 37, keywords: ["valley", "scenic", "hills", "countryside", "grassland"] },
    { id: 110, keywords: ["lake", "water", "serene", "pond", "reflection"] },
    { id: 64, keywords: ["beach", "ocean", "coast", "sea", "sand", "shore"] },
    { id: 76, keywords: ["flowers", "garden", "blooms", "floral", "botanical"] },
    { id: 1018, keywords: ["snow", "winter", "cold", "ice", "frost"] },
  ],
  cityscape: [
    { id: 260, keywords: ["skyline", "downtown", "city", "metropolis", "urban"] },
    { id: 452, keywords: ["buildings", "architecture", "urban", "structure", "skyscraper"] },
    { id: 429, keywords: ["street", "road", "city life", "avenue", "boulevard"] },
    { id: 172, keywords: ["night city", "lights", "urban night", "evening", "nightlife"] },
    { id: 315, keywords: ["bridge", "infrastructure", "crossing", "span", "connection"] },
  ],
  portrait: [
    { id: 338, keywords: ["woman", "female", "portrait", "girl", "lady"] },
    { id: 823, keywords: ["man", "male", "portrait", "guy", "gentleman"] },
    { id: 660, keywords: ["child", "kid", "young", "youth", "toddler"] },
    { id: 26, keywords: ["old person", "elderly", "aged", "senior", "retiree"] },
    { id: 453, keywords: ["group", "people", "crowd", "gathering", "audience"] },
    { id: 177, keywords: ["portrait", "face", "headshot", "person", "model"] },
  ],
  abstract: [
    { id: 1084, keywords: ["pattern", "geometric", "shapes", "design", "motif"] },
    { id: 447, keywords: ["colorful", "vibrant", "bright", "multicolored", "rainbow"] },
    { id: 1069, keywords: ["abstract", "artistic", "non-representational", "surreal", "modern art"] },
    { id: 1020, keywords: ["texture", "surface", "material", "background", "canvas"] },
  ],
  animals: [
    { id: 237, keywords: ["dog", "canine", "pet", "puppy", "hound"] },
    { id: 40, keywords: ["cat", "feline", "pet", "kitten", "domestic animal"] },
    { id: 582, keywords: ["bird", "avian", "flying", "feathered", "wings"] },
    { id: 790, keywords: ["wildlife", "wild animal", "nature", "fauna", "creature"] },
    { id: 659, keywords: ["horse", "equine", "mammal", "pony", "stallion"] },
    { id: 219, keywords: ["bear", "grizzly", "wildlife", "predator", "mammal"] },
    { id: 433, keywords: ["lion", "big cat", "predator", "jungle", "safari"] },
  ],
  technology: [
    { id: 0, keywords: ["computer", "tech", "device", "laptop", "digital"] },
    { id: 48, keywords: ["digital", "screen", "display", "monitor", "electronic"] },
    { id: 160, keywords: ["robot", "ai", "machine", "automation", "artificial intelligence"] },
    { id: 370, keywords: ["futuristic", "sci-fi", "future", "advanced", "innovation"] },
    { id: 1056, keywords: ["gadget", "electronic", "device", "equipment", "smart"] },
    { id: 404, keywords: ["code", "programming", "software", "development", "technology"] },
  ],
  food: [
    { id: 292, keywords: ["meal", "dish", "plate", "dinner", "lunch"] },
    { id: 1080, keywords: ["fruit", "healthy", "fresh", "produce", "nutritious"] },
    { id: 225, keywords: ["dessert", "sweet", "cake", "pastry", "confection"] },
    { id: 493, keywords: ["vegetable", "greens", "produce", "healthy", "organic"] },
    { id: 132, keywords: ["drink", "beverage", "liquid", "refreshment", "cup"] },
    { id: 42, keywords: ["coffee", "cafe", "espresso", "latte", "brew"] },
  ],
  art: [
    { id: 200, keywords: ["painting", "artwork", "canvas", "masterpiece", "artistic"] },
    { id: 349, keywords: ["drawing", "sketch", "illustration", "graphic", "pencil"] },
    { id: 674, keywords: ["sculpture", "statue", "3d art", "carving", "monument"] },
    { id: 423, keywords: ["masterpiece", "classic", "famous", "renowned", "celebrated"] },
    { id: 628, keywords: ["creative", "artistic", "imaginative", "inventive", "innovative"] },
  ],
  space: [
    { id: 701, keywords: ["stars", "galaxy", "universe", "cosmos", "celestial"] },
    { id: 808, keywords: ["planets", "solar system", "cosmic", "orbital", "space"] },
    { id: 683, keywords: ["nebula", "space cloud", "astronomical", "stellar", "cosmic dust"] },
    { id: 717, keywords: ["space", "cosmic", "astronomy", "interstellar", "void"] },
  ],
  fantasy: [
    { id: 326, keywords: ["magical", "fantasy", "mythical", "enchanted", "mystical"] },
    { id: 611, keywords: ["dragon", "creature", "mythological", "beast", "legendary"] },
    { id: 867, keywords: ["medieval", "castle", "kingdom", "fortress", "ancient"] },
    { id: 501, keywords: ["fairy", "magical being", "enchanted", "fantasy creature", "pixie"] },
    { id: 235, keywords: ["unicorn", "mythical", "fantasy", "magical creature", "legend"] },
  ],
  transportation: [
    { id: 111, keywords: ["car", "vehicle", "automobile", "transportation", "wheels"] },
    { id: 191, keywords: ["airplane", "aircraft", "flight", "aviation", "flying"] },
    { id: 1073, keywords: ["train", "locomotive", "railway", "track", "transit"] },
    { id: 331, keywords: ["boat", "ship", "vessel", "nautical", "sailing"] },
  ],
  business: [
    { id: 119, keywords: ["office", "business", "workspace", "corporate", "professional"] },
    { id: 1011, keywords: ["meeting", "conference", "discussion", "collaboration", "teamwork"] },
    { id: 90, keywords: ["laptop", "computer", "work", "business", "desk"] },
  ],
  architecture: [
    { id: 342, keywords: ["modern architecture", "contemporary", "building", "design", "structure"] },
    { id: 164, keywords: ["church", "religious", "historic", "cathedral", "temple"] },
    { id: 309, keywords: ["ancient", "historic", "old", "ruins", "archeological"] },
  ]
};
