// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpwltizvhhwegwctbzap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhwd2x0aXp2aGh3ZWd3Y3RiemFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTUzNDUsImV4cCI6MjA1OTc5MTM0NX0.8AJEsRCJyal3442_ssSUPjpyoe5u5TY8Qvm6RQammV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);